apiVersion: 1

datasources:
  # VictoriaMetrics as Prometheus-compatible datasource
  - name: VictoriaMetrics
    type: prometheus
    access: proxy
    url: http://victoria-metrics:8428
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      customQueryParameters: ''
    version: 1

  # VictoriaLogs datasource
  - name: VictoriaLogs
    type: prometheus
    access: proxy
    url: http://victoria-logs:9428
    editable: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
      # VictoriaLogs uses LogsQL, but can be queried via Prometheus API
    version: 1

  # VictoriaTraces as Jaeger-compatible datasource
  - name: VictoriaTraces
    type: jaeger
    access: proxy
    url: http://victoria-traces:14268
    editable: true
    jsonData:
      # Jaeger UI endpoint
      tracesToLogs:
        datasourceUid: VictoriaLogs
        tags: ['trace_id']
    version: 1
